# Используем официальный Node.js образ
FROM node:18

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем все файлы проекта
COPY . .

# Собираем проект
RUN npm run build

# Указываем порт, на котором будет работать приложение
EXPOSE 5000

# Запускаем приложение
CMD ["npm", "run", "start:prod"]
