import {Navbar} from "@/components/Navbar";
import { Fragment } from "react";

export default function Tracks() {
  return (
   <Fragment>
        <h1>Tracks</h1> 
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>  
        <h1>Tracks</h1>     
    </Fragment>
  );
}
